autoCorrect: true
failFast: false

test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regexes
    - '.*/test/.*'
    - '.*/debug/.*'
    - '.*/androidTest/.*'
    - '.*/generated/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
  exclude-rules:
    - MagicNumber
    - MaxLineLength
    - StringLiteralDuplication
    - ThrowingExceptionsWithoutMessageOrCause
    - LargeClass
    - LongParameterList
    - TooManyFunctions

build:
  maxIssues: 1
  weights:
    complexity: 2
    formatting: 1
    LongParameterList: 1
    comments: 1

processors:
  active: true
  exclude:
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'

console-reports:
  active: true
  exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'BuildFailureReport'

output-reports:
  active: true
  exclude:
  #  - 'PlainOutputReport'
  #  - 'XmlOutputReport'

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  InvalidLoopCondition:
    active: true
  WrongEqualsTypeParameter:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  UnreachableCode:
    active: true
  LateinitUsage:
    active: false
    excludeAnnotatedProperties: ''
    ignoreOnClassesPattern: ''
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: false
  UselessPostfixExpression:
    active: false

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: false
  UnnecessaryTemporaryInstantiation:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames: 'toString,hashCode,equals,finalize'
  SwallowedException:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Error
      - Throwable
  TooGenericExceptionThrown:
    active: true
    exceptions:
      - Error
      - Exception
      - NullPointerException
      - RuntimeException
      - Throwable
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    exceptions: 'IllegalArgumentException,IllegalStateException,IOException'
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 30
  NestedBlockDepth:
    active: true
    threshold: 4
  LongParameterList:
    active: true
    threshold: 15
  LargeClass:
    active: true
    threshold: 200
  ComplexInterface:
    active: true
    threshold: 10
    includeStaticDeclarations: false
  ComplexMethod:
    active: true
    threshold: 10
    ignoreSingleWhenExpression: true
  MethodOverloading:
    active: true
    threshold: 7
  TooManyFunctions:
    active: true
    thresholdInFiles: 26 # sometimes we need to implement long external interface
    thresholdInClasses: 26 # sometimes we need to implement long external interface
    thresholdInInterfaces: 12
    thresholdInObjects: 12
    thresholdInEnums: 12
  ComplexCondition:
    active: true
    threshold: 4
  LabeledExpression:
    active: false
  StringLiteralDuplication:
    active: false # this complains about duplicated logs message, but we don't want to extract them into constants
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'

code-smell:
  active: true
  FeatureEnvy:
    threshold: 0.5
    weight: 0.45
    base: 0.5

style:
  active: true
  ReturnCount:
    active: false
  ThrowsCount:
    active: true
    max: 2
  NewLineAtEndOfFile:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalWhenBraces:
    active: false
  CollapsibleIfStatements:
    active: true
  EqualsNullCall:
    active: true
  ForbiddenComment:
    active: false
    values: 'TODO:,FIXME:,STOPSHIP:'
  ForbiddenImport:
    active: true
    imports: ''
  SpacingBetweenPackageAndImports:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 1
  MethodNameEqualsClassName:
    active: true
    ignoreOverriddenFunction: true
  ModifierOrder:
    active: true
  MagicNumber:
    active: true
    ignoreNumbers: '-1,0,1,2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: true
  WildcardImport:
    active: true
    excludeImports: 'java.util.*,kotlinx.android.synthetic.*,java.security.*'
  SafeCast:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 100
    excludePackageStatements: false
    excludeImportStatements: true
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z$]*'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z$][a-zA-Z_$]*$'
  FunctionNaming:
    active: true
    functionPattern: '^([a-z$][a-zA-Z$0-9]*)|(`.*`)$'
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: true
    minimumFunctionNameLength: 3
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
  ObjectPropertyNaming:
    active: true
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z\d]*'
    privatePropertyPattern: '(_)?[a-z][A-Za-z0-9]*'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 30
  VariableMinLength:
    active: true
    minimumVariableNameLength: 2
  ForbiddenClassName:
    active: true
    forbiddenName: ''
  ProtectedMemberInFinalClass:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  UnnecessaryParentheses:
    active: false
  UnnecessaryInheritance:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix: 'to'
  UseDataClass:
    active: false
  UnnecessaryAbstractClass:
    active: false
  OptionalUnit:
    active: true
  OptionalReturnKeyword:
    active: true
  ExpressionBodySyntax:
    active: false
  UnusedImports:
    active: true # doesn't work when import is used in KDoc
  NestedClassesVisibility:
    active: false
  RedundantVisibilityModifierRule:
    active: true
  FunctionOnlyReturningConstant:
    active: true
    ignoreOverridableFunction: true
    excludedFunctions: 'describeContents'

# *experimental feature*
# Migration rules can be defined in the same config file or a new one
migration:
  active: true
  imports:
  # your.package.Class: new.package.or.Class
  # for example:
  # io.gitlab.arturbosch.detekt.api.Rule: io.gitlab.arturbosch.detekt.rule.Rule

formatting:
  active: true
  ChainWrapping:
    active: true
  CommentSpacing:
    active: true
  Filename:
    active: true
  FinalNewline:
    active: true
  ImportOrdering:
    active: true
  Indentation:
    active: true
    indentSize: 4
    continuationIndentSize: 4
  MaximumLineLength:
    active: false # it duplicates the base rule MaxLineLength
    maxLineLength: 100
  ModifierOrdering:
    active: true
  NoBlankLineBeforeRbrace:
    active: true
  NoConsecutiveBlankLines:
    active: true
  NoEmptyClassBody:
    active: true
  NoItParamInMultilineLambda:
    active: false
  NoLineBreakAfterElse:
    active: true
  NoLineBreakBeforeAssignment:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  NoTrailingSpaces:
    active: true
  NoUnitReturn:
    active: true
  NoUnusedImports:
    active: true
  NoWildcardImports:
    active: true
  ParameterListWrapping:
    active: true
    indentSize: 4
  SpacingAroundColon:
    active: true
  SpacingAroundComma:
    active: true
  SpacingAroundCurly:
    active: true
  SpacingAroundKeyword:
    active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundRangeOperator:
    active: true
  StringTemplate:
    active: true
